export const BLOCK_TYPE = 'BLOCK_TYPE'
export const BLOCK_TYPE_GROUP = 'BLOCK_TYPE_GROUP'

export const ADD_BLOCK_TYPE = 'ADD_BLOCK_TYPE'
export const REMOVE_BLOCK_TYPE = 'REMOVE_BLOCK_TYPE'
export const MOVE_BLOCK_TYPE = 'MOVE_BLOCK_TYPE'

export const ADD_BLOCK_TYPE_GROUP = 'ADD_BLOCK_TYPE_GROUP'
export const REMOVE_BLOCK_TYPE_GROUP = 'REMOVE_BLOCK_TYPE_GROUP'
export const MOVE_BLOCK_TYPE_GROUP = 'MOVE_BLOCK_TYPE_GROUP'
