name: Bug Report
description: Let us know about a problem with Neo
labels:
  - "bug report"
  - "bug report status: new"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please check to make sure your bug hasn't already been reported before proceeding. Please also make sure you correctly follow all instructions when filling out this form. Failure to do so may result in your bug report being closed as invalid.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Details of the bug you've encountered.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Instructions that can be followed to reliably reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What should be expected to happen instead of the buggy behaviour.
  - type: input
    id: neo-version
    attributes:
      label: Neo version
      description: Enter the exact Neo version number you are using.
    validations:
      required: true
  - type: input
    id: craft-cms-version
    attributes:
      label: Craft CMS version
      description: Enter the exact Craft CMS version number you are using.
    validations:
      required: true
  - type: input
    id: neo-propagation-method
    attributes:
      label: What is the affected Neo field's propagation method?
      description: Leave this blank if your Craft install is not multi-site.
  - type: dropdown
    id: neo-eager-loading
    attributes:
      label: Does this issue involve templating, and if so, is eager-loading used?
      options:
        - This is not a templating issue
        - This is a templating issue, and eager loading is not used
        - This is a templating issue, and eager loading is used
    validations:
      required: true
