export const BLOCK = 'BLOCK'

export const BLOCK_PARENT = 'BLOCK_PARENT'
export const BLOCK_PREV_SIBLING = 'BLOCK_PREV_SIBLING'
export const BLOCK_NEXT_SIBLING = 'BLOCK_NEXT_SIBLING'

export const ADD_BLOCK = 'ADD_BLOCK'
export const REMOVE_BLOCK = 'REMOVE_BLOCK'
export const MOVE_BLOCK = 'MOVE_BLOCK'
